import { WorkflowScenario } from "./automation-engine-types";

export const WORKFLOW_SCENARIOS: WorkflowScenario[] = [
  // =========================================================================
  // SCENARIO 01: SALES & PIPELINE GROWTH (PRIMARY DEMO)
  // =========================================================================
  {
    id: "sales",
    title: "Inbound Lead → Qualified Opportunity",
    subtitle: "Turn raw inbound interest into researched, enriched, and scheduled enterprise pipeline without manual data entry.",
    badge: "SALES & REVENUE AUTOMATION",
    category: "Revenue Operations",
    description: "Evaluates inbound web form submissions, performs real-time AI company profiling and contact verification in parallel, calculates predictive fit scores, routes through deterministic decision gates, executes CRM sync & Slack alerts simultaneously, and drafts personalized outreach.",
    triggerEvent: "Inbound Webhook: Form Submission #712",
    executionSequence: [
      ["node-sales-trigger"],
      ["node-sales-research", "node-sales-enrich"],
      ["node-sales-score"],
      ["node-sales-decision"],
      ["node-sales-crm", "node-sales-slack"],
      ["node-sales-outreach"],
    ],
    nodes: [
      {
        id: "node-sales-trigger",
        type: "trigger",
        label: "Inbound Lead",
        sublabel: "Landing Page Webhook",
        category: "Event Trigger",
        iconName: "Zap",
        position: { x: 9, y: 35 },
        status: "idle",
        executionTimeMs: 120,
        badge: "01. TRIGGER",
        techStack: "Cloud Webhook // HTTPS REST",
        processDescription: "Receives raw form payload from landing page and validates email syntax and domain existence.",
        inputs: [
          { label: "Contact Name", value: "Marcus Vance", type: "string" },
          { label: "Work Email", value: "mvance@nexuslogistics.io", type: "string" },
          { label: "Inbound Note", value: "Looking to automate our 50-person ops team", type: "string" },
        ],
        outputs: [
          { label: "Normalized Payload", value: "RAW_LEAD_712", type: "entity" },
          { label: "Clean Domain", value: "nexuslogistics.io", type: "string" },
        ],
        livePayload: {
          leadId: "LEAD-712",
          source: "Landing Page Form",
          ipCountry: "US",
          receivedAt: "Just now",
        },
      },
      {
        id: "node-sales-research",
        type: "ai",
        label: "Company Research",
        sublabel: "Firmographics & Tech Stack",
        category: "AI Intelligence",
        iconName: "Sparkles",
        position: { x: 26, y: 20 },
        status: "idle",
        executionTimeMs: 240,
        badge: "02A. AI PROFILE",
        techStack: "Hastava Semantic Web Intelligence",
        processDescription: "Performs autonomous web research to determine company revenue ($45M ARR), headcount (220 FTE), and tech stack (Salesforce + SAP).",
        inputs: [
          { label: "Target Domain", value: "nexuslogistics.io", type: "string" },
        ],
        outputs: [
          { label: "Company Profile", value: "Nexus Global Logistics ($45M ARR)", type: "entity" },
          { label: "Tech Stack", value: "Salesforce + SAP ERP", type: "string" },
        ],
        livePayload: {
          industry: "Freight Logistics & 3PL",
          hq: "Chicago, IL",
          fundingStage: "Series B / Profitable",
        },
      },
      {
        id: "node-sales-enrich",
        type: "data",
        label: "Contact Verification",
        sublabel: "Exec Identity & Deliverability",
        category: "Data Verification",
        iconName: "Database",
        position: { x: 26, y: 52 },
        status: "idle",
        executionTimeMs: 180,
        badge: "02B. VERIFY",
        techStack: "Clearbit + NeverBounce API",
        processDescription: "Verifies executive title (VP of Operations), LinkedIn persona profile, and confirms 100% email deliverability rating.",
        inputs: [
          { label: "Contact Name", value: "Marcus Vance", type: "string" },
          { label: "Work Email", value: "mvance@nexuslogistics.io", type: "string" },
        ],
        outputs: [
          { label: "Verified Title", value: "VP of Operations (Tier 1 Buyer)", type: "status" },
          { label: "Deliverability", value: "100% Validated (Corporate MX)", type: "status" },
        ],
        livePayload: {
          seniority: "VP / Executive",
          directDialFound: true,
          deliverabilityScore: 1.0,
        },
      },
      {
        id: "node-sales-score",
        type: "ai",
        label: "Intent & Fit Scoring",
        sublabel: "NLP Multi-Factor Model",
        category: "Scoring Engine",
        iconName: "Cpu",
        position: { x: 44, y: 35 },
        status: "idle",
        executionTimeMs: 160,
        badge: "03. SCORING",
        techStack: "Predictive Intent Model",
        processDescription: "Synthesizes firmographics, executive authority, and note sentiment to compute composite ICP fit score (Score: 88/100).",
        inputs: [
          { label: "Firmographics", value: "$45M ARR // 220 FTE", type: "string" },
          { label: "Persona", value: "VP Operations", type: "string" },
          { label: "Need Note", value: "50-person ops team automation", type: "string" },
        ],
        outputs: [
          { label: "Calculated Score", value: "88 / 100 (Enterprise Fit)", type: "score" },
          { label: "Buying Urgency", value: "High (Active Q4 Project)", type: "status" },
        ],
        livePayload: {
          fitGrade: "Tier-1 Enterprise",
          predictedDealSize: "$185,000",
        },
      },
      {
        id: "node-sales-decision",
        type: "logic",
        label: "Qualify Decision Gate",
        sublabel: "ICP Score ≥ 75 Evaluation",
        category: "Logic Gateway",
        iconName: "GitFork",
        position: { x: 62, y: 35 },
        status: "idle",
        executionTimeMs: 80,
        badge: "04. DECISION",
        techStack: "Deterministic Rule Engine",
        processDescription: "Evaluates whether composite ICP score satisfies enterprise threshold (Score 88 ≥ 75). Routes to high-touch executive path.",
        decisionConfig: {
          threshold: 75,
          evaluatedValue: 88,
          operator: ">=",
          yesTargetNodeId: "node-sales-crm",
          noTargetNodeId: "node-sales-nurture",
          conditionLabel: "ICP Score (88) ≥ 75",
        },
        inputs: [
          { label: "Calculated Score", value: "88 / 100", type: "score" },
          { label: "Threshold", value: "75", type: "score" },
        ],
        outputs: [
          { label: "Decision Branch", value: "YES → Enterprise Account Route", type: "status" },
        ],
        livePayload: {
          conditionMet: true,
          evaluatedAtMs: 80,
          branchSelected: "ENTERPRISE_PIPELINE",
        },
      },
      {
        id: "node-sales-crm",
        type: "action",
        label: "CRM Deal Creation",
        sublabel: "HubSpot / Salesforce Sync",
        category: "System Action",
        iconName: "Layers",
        position: { x: 80, y: 18 },
        status: "idle",
        executionTimeMs: 160,
        badge: "05A. CRM SYNC",
        techStack: "Salesforce GraphQL + HubSpot API",
        processDescription: "Creates Enterprise Account, associates VP of Ops contact record, assigns AE owner, and creates $185k pipeline deal.",
        inputs: [
          { label: "Account Name", value: "Nexus Global Logistics", type: "string" },
          { label: "Deal Value", value: "$185,000 ARR", type: "currency" },
        ],
        outputs: [
          { label: "Account ID", value: "SF-ACC-90412", type: "string" },
          { label: "Deal Status", value: "Stage: Discovery Scheduled", type: "status" },
        ],
        livePayload: {
          leadOwnerAssigned: "Sarah Jenkins (Enterprise AE)",
          syncLatency: "142ms",
        },
      },
      {
        id: "node-sales-slack",
        type: "action",
        label: "Slack Alert Dispatched",
        sublabel: "Pings #enterprise-leads",
        category: "Collaboration Action",
        iconName: "Bell",
        position: { x: 80, y: 48 },
        status: "idle",
        executionTimeMs: 110,
        badge: "05B. SLACK PUSH",
        techStack: "Slack Block Kit Webhook",
        processDescription: "Broadcasts rich interactive lead card with company brief, deal metrics, and 1-click meeting calendar to sales team.",
        inputs: [
          { label: "Slack Channel", value: "#enterprise-deals", type: "string" },
          { label: "Priority Level", value: "P1 Immediate Response", type: "status" },
        ],
        outputs: [
          { label: "Message Status", value: "Broadcasted with Action Buttons", type: "status" },
        ],
        livePayload: {
          channelPinged: "#enterprise-deals",
          slackTimestamp: "1728412891.002",
        },
      },
      {
        id: "node-sales-nurture",
        type: "action",
        label: "Educational Nurture",
        sublabel: "Sub-Threshold Fallback",
        category: "Fallback Action",
        iconName: "LifeBuoy",
        position: { x: 80, y: 80 },
        status: "skipped",
        executionTimeMs: 100,
        badge: "FALLBACK",
        techStack: "Marketing Automation Engine",
        processDescription: "Enrolls sub-threshold leads into targeted industry educational content tracks.",
        inputs: [{ label: "Email", value: "lead@domain.com", type: "string" }],
        outputs: [{ label: "Track", value: "Mid-Market Growth Series", type: "status" }],
      },
      {
        id: "node-sales-outreach",
        type: "output",
        label: "Personalized Outreach",
        sublabel: "Executive Brief & Calendar Slot",
        category: "Final Output",
        iconName: "Send",
        position: { x: 95, y: 33 },
        status: "idle",
        executionTimeMs: 190,
        badge: "06. OUTREACH",
        techStack: "Hastava Hyper-Personalized AI Dispatch",
        processDescription: "Generates bespoke meeting invite acknowledging Marcus's 50-person ops challenge with tailored freight automation case studies.",
        inputs: [
          { label: "Recipient", value: "mvance@nexuslogistics.io", type: "string" },
          { label: "Context", value: "50-person ops team + SAP integration", type: "string" },
        ],
        outputs: [
          { label: "Outreach Status", value: "Email Dispatched // Calendar Active", type: "status" },
          { label: "Calendar Slot", value: "Thursday 2:00 PM EST Reserved", type: "date" },
        ],
        livePayload: {
          emailSubject: "Hastava + Nexus Global: Automating the 50-person ops team",
          readRateEstimate: "94%",
        },
      },
    ],
    connections: [
      { id: "conn-1", fromNodeId: "node-sales-trigger", toNodeId: "node-sales-research", status: "inactive" },
      { id: "conn-2", fromNodeId: "node-sales-trigger", toNodeId: "node-sales-enrich", status: "inactive" },
      { id: "conn-3", fromNodeId: "node-sales-research", toNodeId: "node-sales-score", status: "inactive" },
      { id: "conn-4", fromNodeId: "node-sales-enrich", toNodeId: "node-sales-score", status: "inactive" },
      { id: "conn-5", fromNodeId: "node-sales-score", toNodeId: "node-sales-decision", status: "inactive" },
      { id: "conn-6", fromNodeId: "node-sales-decision", toNodeId: "node-sales-crm", label: "YES (Score ≥ 75)", status: "inactive", branchType: "yes" },
      { id: "conn-7", fromNodeId: "node-sales-decision", toNodeId: "node-sales-slack", label: "YES", status: "inactive", branchType: "yes" },
      { id: "conn-8", fromNodeId: "node-sales-decision", toNodeId: "node-sales-nurture", label: "NO (Score < 75)", status: "skipped", branchType: "no" },
      { id: "conn-9", fromNodeId: "node-sales-crm", toNodeId: "node-sales-outreach", status: "inactive" },
      { id: "conn-10", fromNodeId: "node-sales-slack", toNodeId: "node-sales-outreach", status: "inactive" },
    ],
    simulatedOutcome: {
      headline: "Qualified Enterprise Opportunity Dispatched in 1.4s",
      summary: "What traditionally took an SDR and RevOps team 45 minutes of manual context-switching was verified, enriched, scored, synced to CRM, alerted on Slack, and followed up autonomously.",
      beforeManual: {
        duration: "45 Minutes per Lead",
        friction: "Leads sit in inbox queue for hours; SDRs manually Google companies, copy paste info into Salesforce, and draft generic follow-up emails.",
        steps: [
          "Manual email inbox monitoring",
          "Manual LinkedIn & Google company research",
          "Manual contact email verification checks",
          "Subjective, inconsistent lead qualification",
          "Copying data into CRM fields by hand",
          "Manual Slack message to AE team",
          "Drafting delayed generic outreach email",
        ],
      },
      afterAutomated: {
        duration: "1.4 Seconds Total",
        outcome: "100% verified firmographics, calibrated fit scoring, clean CRM hygiene, and hyper-personalized executive outreach ready in seconds.",
        steps: [
          "Instant webhook trigger on submission",
          "Parallel AI company & contact verification",
          "Algorithmic ICP fit scoring (Score: 88/100)",
          "Deterministic qualify decision gate resolution",
          "Parallel CRM deal creation + Slack executive notification",
          "Context-aware executive meeting invite sent",
        ],
      },
      keyMetrics: [
        { label: "Execution Latency", value: "1.42s" },
        { label: "Data Accuracy", value: "100% Verified" },
        { label: "Human Touch Required", value: "0 Minutes" },
        { label: "Lead Response Time", value: "< 2 Seconds" },
      ],
    },
  },

  // =========================================================================
  // SCENARIO 02: OPERATIONS & SUPPLY CHAIN FULFILLMENT
  // =========================================================================
  {
    id: "operations",
    title: "Inbound PO → Automated ERP & Warehouse Dispatch",
    subtitle: "Eliminate manual purchase order data entry, inventory verification, credit checking, and warehouse ticketing.",
    badge: "OPERATIONS & SUPPLY AUTOMATION",
    category: "Operations & Supply Chain",
    description: "Extracts purchase order line items from PDF invoices, cross-references inventory levels in ERP/WMS, checks customer credit limits in parallel, and auto-dispatches warehouse fulfillment manifests.",
    triggerEvent: "MIME Email Event: Attached PO-89412.pdf",
    executionSequence: [
      ["node-ops-trigger"],
      ["node-ops-extract", "node-ops-inventory"],
      ["node-ops-credit"],
      ["node-ops-decision"],
      ["node-ops-warehouse", "node-ops-ledger"],
      ["node-ops-output"],
    ],
    nodes: [
      {
        id: "node-ops-trigger",
        type: "trigger",
        label: "PDF Purchase Order",
        sublabel: "Email Attachment Inbound",
        category: "Document Trigger",
        iconName: "FileText",
        position: { x: 9, y: 35 },
        status: "idle",
        executionTimeMs: 140,
        badge: "01. TRIGGER",
        techStack: "IMAP TLS Inbox Listener // Secure",
        processDescription: "Detects new supplier order email with attached 4-page PDF purchase order.",
        inputs: [
          { label: "Attachment", value: "PO_Nexus_89412.pdf", type: "string" },
          { label: "Sender", value: "procurement@nexus.com", type: "string" },
        ],
        outputs: [
          { label: "File Stream", value: "RAW_PDF_STREAM_4P", type: "entity" },
        ],
        livePayload: {
          fileSize: "1.2 MB",
          receivedAt: "Just now",
        },
      },
      {
        id: "node-ops-extract",
        type: "ai",
        label: "Document AI OCR",
        sublabel: "18 Itemized Line Items & SKUs",
        category: "Document AI",
        iconName: "Cpu",
        position: { x: 26, y: 20 },
        status: "idle",
        executionTimeMs: 260,
        badge: "02A. OCR EXTRACT",
        techStack: "Hastava Multimodal Vision AI",
        processDescription: "Extracts 18 itemized line items, part numbers, unit prices, and tax IDs from PDF.",
        inputs: [
          { label: "Document", value: "PO_Nexus_89412.pdf", type: "string" },
        ],
        outputs: [
          { label: "PO Number", value: "PO-89412 ($64,200.00)", type: "string" },
          { label: "Total Units", value: "1,200 units required", type: "number" },
        ],
        livePayload: {
          lineItemsParsed: 18,
          confidence: 0.998,
        },
      },
      {
        id: "node-ops-inventory",
        type: "data",
        label: "WMS Stock Query",
        sublabel: "Real-Time SAP & Bin Verification",
        category: "Data System",
        iconName: "Database",
        position: { x: 26, y: 52 },
        status: "idle",
        executionTimeMs: 170,
        badge: "02B. INVENTORY",
        techStack: "SAP ERP + HighJump WMS",
        processDescription: "Checks available stock across regional hubs (1,450 units available at Hub A).",
        inputs: [
          { label: "SKU Required", value: "1,200 units", type: "number" },
        ],
        outputs: [
          { label: "Available Stock", value: "1,450 units at Hub A (OK)", type: "number" },
          { label: "Primary Bin", value: "Bin #A-402 (Reserved)", type: "string" },
        ],
        livePayload: {
          hubLocation: "Hub A - Chicago",
          safetyStockRemaining: 250,
        },
      },
      {
        id: "node-ops-credit",
        type: "ai",
        label: "Credit & Margin Check",
        sublabel: "Customer Ledger Balance",
        category: "Finance Verification",
        iconName: "DollarSign",
        position: { x: 44, y: 35 },
        status: "idle",
        executionTimeMs: 130,
        badge: "03. CREDIT",
        techStack: "QuickBooks / NetSuite Sync",
        processDescription: "Evaluates customer credit line ($250k limit, $42k balance) and verifies Net-30 payment terms.",
        inputs: [
          { label: "Customer Account", value: "Nexus Global Logistics", type: "string" },
          { label: "Order Amount", value: "$64,200.00", type: "currency" },
        ],
        outputs: [
          { label: "Credit Standing", value: "Approved // Good Standing", type: "status" },
          { label: "Available Credit", value: "$208,000.00 Remaining", type: "currency" },
        ],
        livePayload: {
          paymentTerms: "Net-30 Approved",
          fraudRiskScore: "0.01 (Low)",
        },
      },
      {
        id: "node-ops-decision",
        type: "logic",
        label: "Fulfillment Decision Gate",
        sublabel: "Stock & Credit Evaluation",
        category: "Logic Gateway",
        iconName: "GitFork",
        position: { x: 62, y: 35 },
        status: "idle",
        executionTimeMs: 80,
        badge: "04. DECISION",
        techStack: "Operational Logic Engine",
        processDescription: "Evaluates inventory sufficiency (1,450 >= 1,200) and credit approval. Routes to automated warehouse dispatch.",
        decisionConfig: {
          threshold: 1200,
          evaluatedValue: 1450,
          operator: ">=",
          yesTargetNodeId: "node-ops-warehouse",
          noTargetNodeId: "node-ops-backorder",
          conditionLabel: "Available Units (1,450) ≥ Required (1,200)",
        },
        inputs: [
          { label: "Available Stock", value: "1,450 units", type: "number" },
          { label: "Credit Standing", value: "Approved", type: "status" },
        ],
        outputs: [
          { label: "Route", value: "YES → Immediate Automated Fulfillment", type: "status" },
        ],
        livePayload: {
          ruleResult: "AUTO_FULFILL",
        },
      },
      {
        id: "node-ops-warehouse",
        type: "action",
        label: "WMS Pick Ticket",
        sublabel: "Barcoded Manifest & Bin Reserve",
        category: "Fulfillment Action",
        iconName: "Truck",
        position: { x: 80, y: 18 },
        status: "idle",
        executionTimeMs: 170,
        badge: "05A. WMS DISPATCH",
        techStack: "WMS API + Zebra Print Queue",
        processDescription: "Generates barcoded pick-pack-ship manifest, reserves stock in bin #A-402, and queues forklift task.",
        inputs: [
          { label: "Order ID", value: "ORD-99412", type: "string" },
          { label: "Bin Location", value: "Hub A // Bin #A-402", type: "string" },
        ],
        outputs: [
          { label: "Manifest Code", value: "MANIFEST-HUB-A-99412", type: "string" },
          { label: "Status", value: "Ready for Pick & Pack", type: "status" },
        ],
        livePayload: {
          pickListPrinted: true,
          estPickup: "Today 3:30 PM",
        },
      },
      {
        id: "node-ops-ledger",
        type: "action",
        label: "General Ledger Post",
        sublabel: "AR Invoice & Revenue Sync",
        category: "Finance Action",
        iconName: "Layers",
        position: { x: 80, y: 48 },
        status: "idle",
        executionTimeMs: 140,
        badge: "05B. AR POST",
        techStack: "NetSuite ERP / SAP Sync",
        processDescription: "Posts $64,200 Accounts Receivable invoice to general ledger and schedules carrier freight pickup.",
        inputs: [
          { label: "Invoice Amount", value: "$64,200.00 Net-30", type: "currency" },
          { label: "Carrier", value: "FedEx Freight Priority", type: "string" },
        ],
        outputs: [
          { label: "Invoice ID", value: "INV-2026-89412", type: "string" },
          { label: "Tracking Code", value: "FX-8941-9281-US", type: "string" },
        ],
        livePayload: {
          ledgerReconciled: true,
          glAccount: "1100-AR-TRADE",
        },
      },
      {
        id: "node-ops-backorder",
        type: "action",
        label: "Emergency Restock PO",
        sublabel: "Out-of-Stock Fallback",
        category: "Fallback Action",
        iconName: "RotateCcw",
        position: { x: 80, y: 80 },
        status: "skipped",
        executionTimeMs: 100,
        badge: "FALLBACK",
        techStack: "Supplier Reorder API",
        processDescription: "Generates automated restock order when inventory drops below safety thresholds.",
        inputs: [{ label: "Deficit", value: "0 units", type: "number" }],
        outputs: [{ label: "Restock PO", value: "STANDBY", type: "status" }],
      },
      {
        id: "node-ops-output",
        type: "output",
        label: "Dispatch Confirmation",
        sublabel: "Buyer Tracking Link Dispatched",
        category: "Final Output",
        iconName: "CheckCircle2",
        position: { x: 95, y: 33 },
        status: "idle",
        executionTimeMs: 120,
        badge: "06. DISPATCHED",
        techStack: "Automated Notification System",
        processDescription: "Dispatches automated order confirmation and live carrier tracking link to customer procurement department.",
        inputs: [{ label: "Tracking Code", value: "FX-8941-9281-US", type: "string" }],
        outputs: [
          { label: "Status", value: "Order In Transit // Expected Delivery Oct 24", type: "status" },
        ],
        livePayload: {
          customerNotified: true,
          opsLatencyTotal: "1.18s",
        },
      },
    ],
    connections: [
      { id: "cops-1", fromNodeId: "node-ops-trigger", toNodeId: "node-ops-extract", status: "inactive" },
      { id: "cops-2", fromNodeId: "node-ops-trigger", toNodeId: "node-ops-inventory", status: "inactive" },
      { id: "cops-3", fromNodeId: "node-ops-extract", toNodeId: "node-ops-credit", status: "inactive" },
      { id: "cops-4", fromNodeId: "node-ops-inventory", toNodeId: "node-ops-credit", status: "inactive" },
      { id: "cops-5", fromNodeId: "node-ops-credit", toNodeId: "node-ops-decision", status: "inactive" },
      { id: "cops-6", fromNodeId: "node-ops-decision", toNodeId: "node-ops-warehouse", label: "YES (Stock OK)", status: "inactive", branchType: "yes" },
      { id: "cops-7", fromNodeId: "node-ops-decision", toNodeId: "node-ops-ledger", label: "YES", status: "inactive", branchType: "yes" },
      { id: "cops-8", fromNodeId: "node-ops-decision", toNodeId: "node-ops-backorder", label: "NO (Out of Stock)", status: "skipped", branchType: "no" },
      { id: "cops-9", fromNodeId: "node-ops-warehouse", toNodeId: "node-ops-output", status: "inactive" },
      { id: "cops-10", fromNodeId: "node-ops-ledger", toNodeId: "node-ops-output", status: "inactive" },
    ],
    simulatedOutcome: {
      headline: "1,200-Unit Purchase Order Processed in 1.18s",
      summary: "Manual PO data entry, stock queries, credit vetting, packing slip printing, and general ledger reconciliation eliminated completely.",
      beforeManual: {
        duration: "30-45 Min per PO",
        friction: "Ops clerk manually types PDF numbers into SAP, checks inventory spreadsheet, emails finance for credit check, and logs into warehouse portal.",
        steps: [
          "Manual reading of 4-page PDF order",
          "Typing SKUs and addresses into SAP ERP",
          "Checking physical warehouse stock table",
          "Waiting for finance credit approval email",
          "Manual creation of shipping label and manifest",
          "Manual general ledger posting in accounting system",
        ],
      },
      afterAutomated: {
        duration: "1.18 Seconds Total",
        outcome: "Zero clerical errors, instantaneous stock reservation, and real-time carrier dispatch with automated accounting reconciliation.",
        steps: [
          "Instant Document AI OCR extraction",
          "Parallel real-time ERP database stock verification",
          "Automated ledger credit verification",
          "Fulfillment logic gate resolution",
          "Parallel WMS pick ticket & general ledger posting",
          "Automated tracking email dispatched to buyer",
        ],
      },
      keyMetrics: [
        { label: "Clerical Error Rate", value: "0.00%" },
        { label: "PO Cycle Time", value: "1.18s vs 45min" },
        { label: "Staff Time Saved", value: "100% Autonomous" },
        { label: "Dispatch Speed", value: "Same-Day Priority" },
      ],
    },
  },

  // =========================================================================
  // SCENARIO 03: CUSTOMER SUPPORT & INCIDENT RESOLUTION
  // =========================================================================
  {
    id: "support",
    title: "Urgent Support Ticket → Contextual Resolution",
    subtitle: "Classify urgency, query customer history, evaluate SLA conditions, and autonomously resolve inquiries in seconds.",
    badge: "SUPPORT & SLA AUTOMATION",
    category: "Customer Experience",
    description: "Detects customer support threads, uses NLP sentiment and intent models, queries past transaction history in CRM/ERP in parallel, calculates carrier expedite surcharges, evaluates approval thresholds, and dispatches verified resolutions.",
    triggerEvent: "Zendesk Webhook: Ticket #99102 Inbound",
    executionSequence: [
      ["node-supp-trigger"],
      ["node-supp-nlp", "node-supp-360"],
      ["node-supp-cost"],
      ["node-supp-decision"],
      ["node-supp-reply", "node-supp-wms"],
      ["node-supp-output"],
    ],
    nodes: [
      {
        id: "node-supp-trigger",
        type: "trigger",
        label: "Customer Ticket",
        sublabel: "Zendesk Inbound Webhook",
        category: "Support Trigger",
        iconName: "LifeBuoy",
        position: { x: 9, y: 35 },
        status: "idle",
        executionTimeMs: 110,
        badge: "01. TRIGGER",
        techStack: "Zendesk / Intercom Webhook",
        processDescription: "Receives urgent customer email inquiry regarding freight delivery expedite.",
        inputs: [
          { label: "Sender", value: "logistics@acme.com", type: "string" },
          { label: "Message", value: "Urgent: Need order PO-8120 delivery moved to Wednesday", type: "string" },
        ],
        outputs: [
          { label: "Ticket ID", value: "TICK-99102", type: "string" },
        ],
        livePayload: {
          ticketPriority: "Urgent",
          inboundChannel: "Email Thread",
        },
      },
      {
        id: "node-supp-nlp",
        type: "ai",
        label: "NLP Intent & Sentiment",
        sublabel: "Urgent Expedite Request",
        category: "NLP Intelligence",
        iconName: "Sparkles",
        position: { x: 26, y: 20 },
        status: "idle",
        executionTimeMs: 220,
        badge: "02A. NLP INTENT",
        techStack: "Hastava Semantic Support Model",
        processDescription: "Classifies ticket intent (delivery expedite -48h), sentiment (urgent constructive), and target order ID (PO-8120).",
        inputs: [
          { label: "Inbound Text", value: "Move PO-8120 to Wednesday. Will cover freight.", type: "string" },
        ],
        outputs: [
          { label: "Intent", value: "Delivery Expedite (-48h)", type: "status" },
          { label: "Urgency Level", value: "P1 Urgent (SLA: 15min)", type: "status" },
        ],
        livePayload: {
          sentiment: "Urgent / Constructive",
          confidence: 0.99,
        },
      },
      {
        id: "node-supp-360",
        type: "data",
        label: "Customer 360 & SLA",
        sublabel: "Tier 1 VIP Account ($412k LTV)",
        category: "Customer Data",
        iconName: "Database",
        position: { x: 26, y: 52 },
        status: "idle",
        executionTimeMs: 150,
        badge: "02B. CUST 360",
        techStack: "Salesforce CRM + Graph DB",
        processDescription: "Queries customer master record ($412k LTV, Tier 1 VIP) and contractual SLA response commitments.",
        inputs: [
          { label: "Account", value: "Acme Corp", type: "string" },
        ],
        outputs: [
          { label: "Account Tier", value: "Tier 1 Enterprise (VIP)", type: "status" },
          { label: "SLA Commitment", value: "99.9% 1-Hour Resolution", type: "status" },
        ],
        livePayload: {
          ltv: "$412,000",
          accountRep: "David Miller",
        },
      },
      {
        id: "node-supp-cost",
        type: "ai",
        label: "Transit Fee Surcharge",
        sublabel: "Express Freight Rate Calc",
        category: "Rate Engine",
        iconName: "DollarSign",
        position: { x: 44, y: 35 },
        status: "idle",
        executionTimeMs: 120,
        badge: "03. RATE CALC",
        techStack: "Carrier API + Rate Matrix",
        processDescription: "Calculates carrier surcharge for moving dock departure forward 48 hours (+$420 Express Air freight fee).",
        inputs: [
          { label: "Order ID", value: "PO-8120", type: "string" },
          { label: "Expedite Target", value: "Wednesday 10:00 AM", type: "string" },
        ],
        outputs: [
          { label: "Expedite Cost", value: "$420 Express Freight Fee", type: "currency" },
          { label: "Carrier Slot", value: "Flight FX-410 Confirmed", type: "status" },
        ],
        livePayload: {
          rateCalculated: "$420.00",
          carrierRouteAvailable: true,
        },
      },
      {
        id: "node-supp-decision",
        type: "logic",
        label: "Auto-Approve Gate",
        sublabel: "VIP Tier & Fee Threshold",
        category: "Policy Gateway",
        iconName: "GitFork",
        position: { x: 62, y: 35 },
        status: "idle",
        executionTimeMs: 70,
        badge: "04. DECISION",
        techStack: "Autonomous Policy Engine",
        processDescription: "Evaluates policy rule: VIP Tier 1 accounts with pre-authorized expedite fees under $500 are auto-approved without human manager signoff.",
        decisionConfig: {
          threshold: 500,
          evaluatedValue: 420,
          operator: "<=",
          yesTargetNodeId: "node-supp-reply",
          noTargetNodeId: "node-supp-escalate",
          conditionLabel: "Fee ($420) ≤ Auto-Approval Limit ($500)",
        },
        inputs: [
          { label: "Expedite Fee", value: "$420.00", type: "currency" },
          { label: "Policy Limit", value: "$500.00 Limit", type: "currency" },
        ],
        outputs: [
          { label: "Policy Result", value: "YES → Auto-Approved & Committed", type: "status" },
        ],
        livePayload: {
          policyAuthorized: true,
          auditLogCreated: true,
        },
      },
      {
        id: "node-supp-reply",
        type: "action",
        label: "Resolution Reply Sent",
        sublabel: "Delivery Commitment Email",
        category: "Customer Action",
        iconName: "Send",
        position: { x: 80, y: 18 },
        status: "idle",
        executionTimeMs: 150,
        badge: "05A. REPLY",
        techStack: "Hastava Support Engine",
        processDescription: "Sends hyper-personalized confirmation email to buyer confirming Wednesday delivery window and tracking details.",
        inputs: [
          { label: "Customer Email", value: "logistics@acme.com", type: "string" },
          { label: "New Delivery", value: "Wednesday 10:00 AM", type: "string" },
        ],
        outputs: [
          { label: "Email Sent", value: "Delivered to Acme Logistics", type: "status" },
        ],
        livePayload: {
          csatPredicted: "5/5",
          emailDelivered: true,
        },
      },
      {
        id: "node-supp-wms",
        type: "action",
        label: "WMS Lane Re-Tag",
        sublabel: "Pallet Re-Tagged to Express",
        category: "Fulfillment Action",
        iconName: "Truck",
        position: { x: 80, y: 48 },
        status: "idle",
        executionTimeMs: 140,
        badge: "05B. WMS RE-TAG",
        techStack: "WMS API + RFID Gateway",
        processDescription: "Re-tags physical warehouse pallet to Express Lane 04 for immediate flight loading.",
        inputs: [
          { label: "Dock Lane", value: "Dock Lane 04 (Express Air)", type: "string" },
          { label: "Pallet Tag", value: "RFID #PL-8940-EX", type: "string" },
        ],
        outputs: [
          { label: "WMS Updated", value: "Pallet Staged at Dock 04", type: "status" },
        ],
        livePayload: {
          dockStaged: true,
          forkliftAssigned: "Operator #12",
        },
      },
      {
        id: "node-supp-escalate",
        type: "action",
        label: "Human Escalation",
        sublabel: "Tier 3 On-Call Pager",
        category: "Fallback Action",
        iconName: "LifeBuoy",
        position: { x: 80, y: 80 },
        status: "skipped",
        executionTimeMs: 100,
        badge: "FALLBACK",
        techStack: "PagerDuty / Slack Escalation",
        processDescription: "Pages human supervisor with pre-filled context if policy limits are exceeded.",
        inputs: [{ label: "Reason", value: "Policy Threshold", type: "string" }],
        outputs: [{ label: "Status", value: "STANDBY", type: "status" }],
      },
      {
        id: "node-supp-output",
        type: "output",
        label: "Ticket Closed // SLA Met",
        sublabel: "SLA Met in Under 2 Seconds",
        category: "Final Output",
        iconName: "CheckCircle2",
        position: { x: 95, y: 33 },
        status: "idle",
        executionTimeMs: 90,
        badge: "06. CLOSED",
        techStack: "Zendesk API Closure",
        processDescription: "Closes support ticket with resolution summary and logs 100% SLA compliance metric.",
        inputs: [{ label: "Resolution Time", value: "1.16 Seconds", type: "string" }],
        outputs: [
          { label: "Ticket Status", value: "Resolved & Closed (SLA 100%)", type: "status" },
        ],
        livePayload: {
          slaBreachAvoided: true,
          csatScore: 5.0,
        },
      },
    ],
    connections: [
      { id: "csupp-1", fromNodeId: "node-supp-trigger", toNodeId: "node-supp-nlp", status: "inactive" },
      { id: "csupp-2", fromNodeId: "node-supp-trigger", toNodeId: "node-supp-360", status: "inactive" },
      { id: "csupp-3", fromNodeId: "node-supp-nlp", toNodeId: "node-supp-cost", status: "inactive" },
      { id: "csupp-4", fromNodeId: "node-supp-360", toNodeId: "node-supp-cost", status: "inactive" },
      { id: "csupp-5", fromNodeId: "node-supp-cost", toNodeId: "node-supp-decision", status: "inactive" },
      { id: "csupp-6", fromNodeId: "node-supp-decision", toNodeId: "node-supp-reply", label: "YES (Within Policy)", status: "inactive", branchType: "yes" },
      { id: "csupp-7", fromNodeId: "node-supp-decision", toNodeId: "node-supp-wms", label: "YES", status: "inactive", branchType: "yes" },
      { id: "csupp-8", fromNodeId: "node-supp-decision", toNodeId: "node-supp-escalate", label: "NO (Exceeds Policy)", status: "skipped", branchType: "no" },
      { id: "csupp-9", fromNodeId: "node-supp-reply", toNodeId: "node-supp-output", status: "inactive" },
      { id: "csupp-10", fromNodeId: "node-supp-wms", toNodeId: "node-supp-output", status: "inactive" },
    ],
    simulatedOutcome: {
      headline: "Urgent SLA Escalation Resolved in 1.16s",
      summary: "Customer freight expedite inquiry analyzed, verified against VIP account thresholds, auto-approved, and dispatched with carrier updates instantly.",
      beforeManual: {
        duration: "2-4 Hours Average Response",
        friction: "Customer email sits in shared queue; agent checks Salesforce, messages warehouse manager on Slack, waits for cost approval, and manually writes back.",
        steps: [
          "Ticket waits in unassigned triage queue",
          "Agent manually looks up order in ERP and CRM",
          "Agent Slacks warehouse manager to check carrier slot",
          "Waiting for finance manager approval on $420 expedite fee",
          "Manually typing response email and updating Zendesk",
          "Manual call to warehouse dock master to re-tag pallet",
        ],
      },
      afterAutomated: {
        duration: "1.16 Seconds Total",
        outcome: "Autonomous intent detection, instant policy verification, and zero-human-lag resolution with full audit logging.",
        steps: [
          "Instant Zendesk ticket ingestion",
          "Parallel NLP intent & Customer 360 query",
          "Automated carrier slot rate calculation",
          "Autonomous policy threshold decision (Score: Approved)",
          "Parallel customer reply dispatch & warehouse lane re-tagging",
          "Automated Zendesk ticket closure with SLA audit log",
        ],
      },
      keyMetrics: [
        { label: "SLA Resolution Time", value: "1.16s vs 3 hours" },
        { label: "First Contact Resolution", value: "100%" },
        { label: "Customer CSAT", value: "5.0 / 5.0" },
        { label: "Human Effort", value: "0 Minutes" },
      ],
    },
  },
];
